---

- name: Install openldap
  yum: name={{ item }} state=installed
  with_items: openldap_server_pkgs

- name: Delete the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -s {{ openldap_server_rootpw }}
  register: root_password

- name: Copy the eduperson schema
  copy: src=eduperson.schema dest=/etc/openldap/schema/eduperson.schema mode=0444
  notify:
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf.j2 dest={{ openldap_server_app_path }}/slapd.conf
  notify:
   - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf
